### ISSUE TITLE
Label text size

### ISSUE THREAD

**Issue by matejv** [cidrblock/dld4e#5]
Hi. That looks to be a very promising tool to possibly automate generation of network diagrams.

But is there a way to increase the size of icon and connection labels? The defaults are kind of small.

**Comment by cidrblock** [comment]
The labels should be sized to fit within the space they have.  Do you have an example yaml?

**Comment by matejv** [comment]
Oh, I see. Thanks for the answer.

Well, that works for icon labels. But connections labels are always the same size. For example:

```
diagram:
  fill: "white"
  rows: 5
  columns: 5
  gridLines: true
cisco: &cisco
  x: "+2"
  y: "+2"
  w: "1.5"
  h: "1.5"
  fill: "none"
  stroke: "none"
  iconFamily: "cisco"
  icon: "router"
icons:
  router1: {<<: *cisco, x: 1, y: 1 }
  router2: {<<: *cisco}
connections:
  - {endpoints: ["router1:labelstart","router2:labelend"]}
```

Ideally you could define labels the same way you can define notes. But instead of placing it on the diagram with `x` and `y` you would reference it in one or more icons or connections and the app would place it in an appropriate place.

Alternatively just some controls over text size and possibly placement from start/end of connection would be great.
